import Link from "next/link";

export interface NewsItem { id: string; title: string; slug: string; excerpt: string | null; image_url: string | null; category: string; published_at: string | null; created_at: string; }
export interface DestinationItem { id: string; name: string; slug: string; description: string | null; image_url: string | null; category: string | null; location: string | null; opening_hours: string | null; }

interface Props { newsItems: NewsItem[]; featuredNewsItems: NewsItem[]; featuredDestinations: DestinationItem[]; newsTotalCount: number; newsUnavailable: boolean; }
const fallback = "/og-image.png";
const categories = ["Berita", "Kabar Baik", "Wisata", "Kuliner", "Budaya", "Bisnis", "Event"];
const date = (value: string | null) => value ? new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Gorontalo";

function Meta({ item, number }: { item: NewsItem; number?: number }) { return <p className="text-[11px] font-medium text-[#868686]">{number ? `[No. ${String(number).padStart(3, "0")}] ` : ""}{item.category || "Berita"} <span className="mx-1 text-[#f0bf75]">●</span> oleh Gorontalo Unite <span className="mx-1 text-[#f0bf75]">●</span> {date(item.published_at ?? item.created_at)}</p>; }
function ImageBox({ src, alt, className = "" }: { src: string | null; alt: string; className?: string }) { return <div className={`overflow-hidden bg-[#e9e9e9] ${className}`}>{src ? <img src={src} alt={alt} className="size-full object-cover transition duration-500 hover:scale-105" /> : null}</div>; }
function PostCard({ item, index, featured = false }: { item: NewsItem; index: number; featured?: boolean }) { return <article className={`group bg-white ${featured ? "grid gap-0 md:grid-cols-[1.1fr_.9fr]" : ""}`}><Link href={`/berita/${item.slug}`} className={featured ? "contents" : "block"}><ImageBox src={item.image_url} alt={item.title} className={featured ? "aspect-[4/3] md:h-full md:aspect-auto" : "aspect-[4/3]"} /><div className={featured ? "flex flex-col justify-center p-6 sm:p-9" : "p-5"}><Meta item={item} number={index} /><h3 className={`mt-4 font-serif leading-[1.08] text-[#2f2f2f] ${featured ? "text-3xl sm:text-5xl" : "text-2xl"}`}>{item.title}</h3>{item.excerpt ? <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-[#868686]">{item.excerpt}</p> : null}<span className="mt-5 inline-block text-xs font-semibold text-[#2f2f2f] underline decoration-[#f0bf75] underline-offset-4">Baca selengkapnya</span></div></Link></article>; }

export default function LandingPage({ newsItems, featuredNewsItems, featuredDestinations }: Props) {
  const posts = newsItems.length ? newsItems : [];
  const featured = featuredNewsItems[0] ?? posts[0];
  const recent = posts.filter((post) => post.id !== featured?.id).slice(0, 6);
  const editors = featuredNewsItems.length ? featuredNewsItems : posts.slice(0, 3);
  return <main className="bg-[#f5f5f3] text-[#2f2f2f]">
    <section className="border-b border-[#dedede] px-5 pt-28 md:px-10 md:pt-36"><div className="mx-auto max-w-7xl pb-12"><div className="flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold uppercase tracking-[.08em] text-[#555]"><span>Berita lokal</span><span>City Guide</span><span>Kabar baik</span><span>Agenda Gorontalo</span></div><div className="mt-10 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#f0bf75]">Gorontalo Unite</p><h1 className="mt-4 max-w-4xl font-serif text-5xl leading-[.95] sm:text-7xl">Kabar, cerita, dan tempat yang patut ditemukan di Gorontalo.</h1></div><div className="rounded-2xl bg-[#2f2f2f] p-7 text-white"><p className="font-serif text-2xl">Jangan lewatkan kabar baik.</p><p className="mt-2 text-sm leading-relaxed text-white/70">Ringkasan pilihan Gorontalo Unite dikirim langsung ke inbox Anda.</p><form className="mt-5 flex border-b border-white/40 pb-2"><input aria-label="Email" placeholder="Masukkan email" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/50" /><button type="button" className="text-xs font-bold uppercase tracking-widest text-[#f0bf75]">Ikuti</button></form></div></div></div></section>

    <section className="border-b border-[#dedede] bg-white px-5 py-4 md:px-10"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto no-scrollbar">{categories.map((label) => <Link key={label} href={label === "Wisata" ? "/wisata" : label === "Event" ? "/event" : "/berita"} className="shrink-0 rounded-full border border-[#dedede] px-4 py-2 text-xs font-semibold transition hover:border-[#2f2f2f]">{label}</Link>)}</div></section>

    <section className="px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-7xl">{featured ? <PostCard item={featured} index={19} featured /> : <div className="grid min-h-[420px] place-items-center bg-white text-sm text-[#868686]">Berita pilihan sedang disiapkan.</div>}</div></section>

    <section className="bg-[#f0bf75] px-5 py-10 md:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em]">Berita pilihan</p><h2 className="mt-2 font-serif text-4xl">Recent posts</h2></div><Link href="/berita" className="text-xs font-bold uppercase tracking-widest underline">Lihat semua</Link></div><div className="mt-8 grid gap-px bg-[#2f2f2f] sm:grid-cols-2 lg:grid-cols-3">{recent.slice(0, 6).map((item, index) => <PostCard key={item.id} item={item} index={22 - index} />)}</div></div></section>

    <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b border-[#dedede] pb-5"><h2 className="font-serif text-4xl">Editor’s choice</h2><Link href="/berita" className="text-xs font-bold uppercase tracking-widest">Selengkapnya →</Link></div><div className="mt-8 grid gap-5 lg:grid-cols-3">{editors.slice(0, 3).map((item, index) => <PostCard key={item.id} item={item} index={18 - index} />)}</div></div></section>

    <section className="bg-white px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b border-[#dedede] pb-5"><h2 className="font-serif text-4xl">Watch</h2><Link href="/event" className="text-xs font-bold uppercase tracking-widest">Lihat event →</Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[...recent, ...editors].slice(0, 3).map((item, index) => <article key={item.id} className="bg-[#f5f5f3] p-4"><ImageBox src={item.image_url} alt={item.title} className="aspect-video" /><Meta item={item} number={16 - index} /><h3 className="mt-3 font-serif text-2xl leading-tight">{item.title}</h3><p className="mt-2 text-sm text-[#868686]">Cerita visual dan agenda yang layak diikuti.</p></article>)}</div></div></section>

    <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="bg-[#2f2f2f] p-9 text-white"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#f0bf75]">Gorontalo Unite</p><h2 className="mt-5 font-serif text-4xl leading-tight">Cerita lokal yang membuka rasa ingin tahu.</h2><p className="mt-5 text-sm leading-relaxed text-white/70">Gorontalo Unite menghubungkan berita, rekomendasi, komunitas, dan orang-orang yang membuat daerah ini terus bergerak.</p><Link href="/about" className="mt-8 inline-block text-xs font-bold uppercase tracking-widest text-[#f0bf75]">Tentang kami →</Link></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#f0bf75]">Discover more stories</p><h2 className="mt-3 font-serif text-5xl">Terus jelajahi Gorontalo.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{featuredDestinations.slice(0, 2).map((place) => <Link href={`/wisata/${place.slug}`} key={place.id} className="group bg-white p-4"><ImageBox src={place.image_url} alt={place.name} className="aspect-[4/3]" /><p className="mt-4 text-xs font-semibold uppercase tracking-widest text-[#f0bf75]">{place.category || "City Guide"}</p><h3 className="mt-2 font-serif text-2xl">{place.name}</h3><p className="mt-2 text-sm text-[#868686]">{place.location || "Gorontalo"}</p></Link>)}</div></div></div></section>

    <section className="bg-[#2f2f2f] px-5 py-16 text-white md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#f0bf75]">Agenda</p><h2 className="mt-3 font-serif text-5xl">Event & komunitas</h2><div className="mt-9 grid gap-px bg-white/20 md:grid-cols-3">{["Event minggu ini", "Kirim acara", "Buka kalender"].map((item, index) => <Link href="/event" key={item} className="bg-[#2f2f2f] p-6 transition hover:bg-[#f0bf75] hover:text-[#2f2f2f]"><p className="text-xs text-[#f0bf75] group-hover:text-[#2f2f2f]">[0{index + 1}]</p><h3 className="mt-12 font-serif text-3xl">{item}</h3><span className="mt-4 block text-xs font-bold uppercase tracking-widest">Eksplor →</span></Link>)}</div></div></section>
  </main>;
}
