import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Wisata Gorontalo | Gorontalo Unite", description: "Direktori tempat wisata pilihan di Gorontalo." };

export default async function WisataPage() {
  const supabase = await createClient();
  const { data: places } = await supabase.from("tourism_places").select("id,name,slug,description,image_url,category,location,featured").eq("published", true).order("featured", { ascending: false }).order("updated_at", { ascending: false });
  return <main className="min-h-screen bg-stone-50 pb-20 dark:bg-zinc-950"><section className="mx-auto max-w-7xl px-4 pt-12 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.24em] text-amber-600">City Guide</p><div className="mt-3 flex flex-col gap-4 border-b border-stone-200 pb-10 sm:flex-row sm:items-end sm:justify-between dark:border-zinc-800"><div><h1 className="font-display text-4xl font-bold text-gray-950 dark:text-white sm:text-6xl">Wisata Gorontalo</h1><p className="mt-3 max-w-2xl text-gray-500 dark:text-gray-400">Temukan tempat untuk dikunjungi, lengkap dengan lokasi dan informasi praktis.</p></div><Link href="/" className="text-sm text-gray-500 hover:text-amber-700">← Kembali ke beranda</Link></div></section><section className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8">{!places?.length ? <Empty title="Direktori wisata sedang disiapkan" text="Tempat pilihan Gorontalo akan segera hadir di City Guide." /> : <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{places.map((place) => <Link key={place.id} href={`/wisata/${place.slug}`} className="group overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-black/5 transition hover:-translate-y-1 hover:shadow-xl dark:bg-zinc-900 dark:ring-white/10"><div className="relative aspect-[4/3] bg-amber-100">{place.image_url ? <Image src={place.image_url} alt={place.name} fill unoptimized className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-end bg-gradient-to-br from-amber-200 to-orange-100 p-5 text-sm font-medium text-amber-800">Gorontalo City Guide</div>}</div><div className="p-5"><div className="flex gap-2 text-xs font-semibold uppercase tracking-wide text-amber-700"><span>{place.category || "Wisata"}</span>{place.location && <span className="text-gray-400">· {place.location}</span>}</div><h2 className="mt-2 text-xl font-semibold text-gray-900 dark:text-white">{place.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-gray-500 dark:text-gray-400">{place.description}</p></div></Link>)}</div>}</section></main>;
}
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-3xl border border-dashed border-stone-300 bg-white px-6 py-24 text-center dark:border-zinc-700 dark:bg-zinc-900"><h2 className="font-display text-2xl font-semibold text-gray-800 dark:text-gray-100">{title}</h2><p className="mt-2 text-sm text-gray-500">{text}</p></div>; }
