-- Bring the site's reel categories back in line with the archive.
--
-- Both were filled from the same spreadsheet, but at different moments. The
-- site's values were frozen when the reels were seeded on 13 September; the
-- archive has been annotated since -- 2,426 rows then, all 4,858 now -- so a
-- quarter of them had drifted apart. The archive is the working copy and wins.
--
-- 297 of 1163 reels change. The largest moves:
--   Lifestyle        -> Tourism              54
--   News             -> Regional             40
--   News             -> Paket Narasi Daerah  26
--   Event            -> Sponsored            24
--   Tourism          -> Lifestyle            15
--   Culinary         -> Sponsored            12
--   Untold Story     -> Culture              10
--   News             -> Lifestyle            9
--
-- Three of these categories are new to the site. News empties completely: the
-- archive calls that desk Regional, which is also what the public nav has
-- always called it, so the rename only ends an inconsistency that was already
-- there. DEFAULT_REEL_CATEGORIES gains Regional, People and Paket Narasi
-- Daerah in the same change, or the reels landing in them would have no shelf
-- to appear on.
--
-- One reel is annotated "x" in the archive, meaning unclassified. It is left
-- as it is and given no shelf.

update public.reels as r
   set category = v.category
  from (values
  ('C-3snDfhfqK','Paket Narasi Daerah'),
  ('C-G57eBBwmL','Paket Narasi Daerah'),
  ('C-MF5wwhmD8','Paket Narasi Daerah'),
  ('C-TzTWpBgTy','Paket Narasi Daerah'),
  ('C-ZI4nFhms7','Paket Narasi Daerah'),
  ('C-b9ZlfPy67','Tourism'),
  ('C-eGzzfBn9m','Paket Narasi Daerah'),
  ('C-hr5acyKRV','Tourism'),
  ('C-lrJkEJ1mY','Paket Narasi Daerah'),
  ('C-q0t5gJ5DD','Paket Narasi Daerah'),
  ('C-v8r6hh4WM','Paket Narasi Daerah'),
  ('C-wvmA_vQBd','Tourism'),
  ('C00jjRGRSrP','Untold Story'),
  ('C03srhSyhQs','Lifestyle'),
  ('C0DrAPFuDuS','Tourism'),
  ('C0LVmynh9jY','Sponsored'),
  ('C0UC_DwB9Qz','Sponsored'),
  ('C1jNZttyI0l','Sponsored'),
  ('C2MhHI6Sska','Sponsored'),
  ('C2OiZ1RS_9T','Paket Narasi Daerah'),
  ('C2ji5HayEr6','Regional'),
  ('C3YCw5uSY-F','Regional'),
  ('C3v5ck_hH4I','Lifestyle'),
  ('C40UcqghLF0','Culture'),
  ('C46iavqhb43','Lifestyle'),
  ('C5-opNVBUbS','Regional'),
  ('C5-uYaeBrF8','Regional'),
  ('C50aCP5SOeg','Lifestyle'),
  ('C54gOS7BaCO','Culture'),
  ('C55S1ONhhjx','Regional'),
  ('C5K7YZGB4wM','Culture'),
  ('C5TZra7htFU','Regional'),
  ('C5YYPJxhn0j','Culture'),
  ('C5ZwlpPhzzZ','Sponsored'),
  ('C5e6yl5hTd5','Regional'),
  ('C5iZ9InhUEj','Culture'),
  ('C60erzDOwDK','Regional'),
  ('C6BM0f_hYVk','Regional'),
  ('C6C70h6hWeJ','Regional'),
  ('C6DG-SUyjo1','Regional'),
  ('C6F6kKjhrO0','Regional'),
  ('C6XmKRzyS3h','Tourism'),
  ('C6vUXDSOUGw','Regional'),
  ('C6vcD7TOa9j','Tourism'),
  ('C7GcFper2-n','Culinary'),
  ('C7JUnnXBSEI','Lifestyle'),
  ('C7V80FgSfBg','Lifestyle'),
  ('C7Y654TSUPY','Regional'),
  ('C7bh0Z1BzBQ','Tourism'),
  ('C83XMVWhAn4','Tourism'),
  ('C8Yr7k7vTlp','Tourism'),
  ('C8a8XYvPP9f','Regional'),
  ('C8dWH5NBXcO','Event'),
  ('C8v0SyoPyJQ','Tourism'),
  ('C9D39VWhGoY','Tourism'),
  ('C9Ko9yeBMhE','Regional'),
  ('C9MU08CBLru','Regional'),
  ('C9O_8pIhYTj','Regional'),
  ('C9RCsntBBqJ','Regional'),
  ('C9TXRRRh7Of','Regional'),
  ('C9UmCP7yc5-','Regional'),
  ('C9UpqGlynlc','Regional'),
  ('C9ekRpLhD2Q','Regional'),
  ('C9i3fhQyAQX','Regional'),
  ('C9jK2H8B9st','Regional'),
  ('C9rWGKhOdA-','Tourism'),
  ('C9tkO8UB6PI','Lifestyle'),
  ('C_8BusjhIpu','Lifestyle'),
  ('C_O8C96BHJs','Paket Narasi Daerah'),
  ('C_SoiVYvjNv','Regional'),
  ('C_U39CCBR9v','Paket Narasi Daerah'),
  ('C_XNToMhF0P','Tourism'),
  ('C_b6DWvh7kv','Paket Narasi Daerah'),
  ('C_g8WS5Bu4_','Paket Narasi Daerah'),
  ('C_hsGdjBxh9','Regional'),
  ('C_iBhZRhsm7','Tourism'),
  ('C_mUDdQBIGw','Paket Narasi Daerah'),
  ('C_t6mq9pjag','Paket Narasi Daerah'),
  ('C_zBu4ap9mb','Paket Narasi Daerah'),
  ('Calj3vjgjAT','Tourism'),
  ('Cc9nWwAAmFL','Sponsored'),
  ('CecglUCrgns','Event'),
  ('CefMKe9h5ml','Lifestyle'),
  ('CegzPvHhDYq','Lifestyle'),
  ('CervO8sAvDH','Sponsored'),
  ('CfOF-00gH42','Tourism'),
  ('CgGpVkKgBml','Tourism'),
  ('CgTmnUIA8-B','Tourism'),
  ('Ch3Qb27B8x1','Regional'),
  ('ChWFAbAADWV','Lifestyle'),
  ('Cha6Xb-Axud','Tourism'),
  ('CiozWqVgd9t','Lifestyle'),
  ('Cj142cJgDwZ','Lifestyle'),
  ('CjOwWzjgJ3S','Tourism'),
  ('Ck40oXTAO3y','Lifestyle'),
  ('CnI36EjBYw3','Tourism'),
  ('Cozb8wwhT2g','Tourism'),
  ('CpcJDlZujZZ','Tourism'),
  ('Cped2YkScqi','Culture'),
  ('CponPibgqf9','Lifestyle'),
  ('Cq7ftEkoSLu','Lifestyle'),
  ('CqZCTwjShxq','Tourism'),
  ('Cr1z9KfAyuF','Tourism'),
  ('Crzr-RqAI3s','Tourism'),
  ('CssiUaoAS7W','Sponsored'),
  ('Ct1e5ZjAm1m','Tourism'),
  ('CtDwjWornmn','Regional'),
  ('CtYde8OgnBW','Sponsored'),
  ('Ct_O24wOFHc','Tourism'),
  ('CtgB6eHAzfw','Lifestyle'),
  ('CuUTSQ_g4F9','Lifestyle'),
  ('Cv573VFh5rS','Tourism'),
  ('Cv8vW21NedN','Tourism'),
  ('CvG8WYUhA5s','Lifestyle'),
  ('CvRkJS0BIIZ','Tourism'),
  ('Cw2e7qPBlef','Tourism'),
  ('Cw9TKOWBtpQ','Sponsored'),
  ('CwCiXOKhqIQ','Tourism'),
  ('CwCv54MBI2N','Lifestyle'),
  ('CwMuKQRB4Kl','Sponsored'),
  ('CweoE0lhilL','Sponsored'),
  ('Cwo19NEh4V_','Tourism'),
  ('Cwp1Qo4hhcu','Tourism'),
  ('Cx6yAtkypx1','Sponsored'),
  ('CxAWEoThTqA','Culinary'),
  ('CxH3lbWhKls','Regional'),
  ('CxVM3bOhbOs','Sponsored'),
  ('Cxg7Go7N6ml','Tourism'),
  ('Cxh6CmMB8-t','Tourism'),
  ('CxrJwEySSsh','Sponsored'),
  ('CxsehRcyr47','Sponsored'),
  ('Cxt4JXtO-Rv','Tourism'),
  ('Cy0SWxvB6ow','Tourism'),
  ('CyI0Gfahk5v','Culinary'),
  ('CyIa7V2Oowp','Untold Story'),
  ('CyNoJDWrw6O','Tourism'),
  ('CyiYjnQvl5y','Regional'),
  ('CyntzzQPV6s','Tourism'),
  ('CzSsMl4hbKl','Sponsored'),
  ('Czu-w7_hYlP','Tourism'),
  ('DA2IBaMSQnp','Regional'),
  ('DA5-cffy8wC','Event'),
  ('DA7Ge73Ja_m','Paket Narasi Daerah'),
  ('DAFIM_VJbAX','Paket Narasi Daerah'),
  ('DALWJnkhyt6','Culinary'),
  ('DAcTpo1J4pl','Paket Narasi Daerah'),
  ('DAp_N-IJpoa','Paket Narasi Daerah'),
  ('DBATx83J9ra','Paket Narasi Daerah'),
  ('DBDMEOupUl4','Event'),
  ('DBDPp3dyI5U','Tourism'),
  ('DBEMaX2JHtR','Event'),
  ('DBIfLcnI92g','Tourism'),
  ('DBP_JBqJnth','Paket Narasi Daerah'),
  ('DBSyKwkzKMi','Tourism'),
  ('DBVP6rbBsf_','Paket Narasi Daerah'),
  ('DBXjNomBBi2','Regional'),
  ('DBiMUJgBFCs','Sponsored'),
  ('DBlBpdJSPaX','Tourism'),
  ('DBpeepsh47f','Sponsored'),
  ('DBpnTygOJEX','Lifestyle'),
  ('DC0Q9hBTnG4','Event'),
  ('DCardN6o4Mo','Tourism'),
  ('DCjUI4hzhvA','Event'),
  ('DCjbqOLMUGW','Tourism'),
  ('DCkmASOB4nc','Tourism'),
  ('DCoUXfuzZyI','Sponsored'),
  ('DCwEjThzuH5','Lifestyle'),
  ('DCx9uASypuA','Sponsored'),
  ('DD8Ur7pTMJ-','Regional'),
  ('DD9Y8vlvR_Y','Paket Narasi Daerah'),
  ('DDUc75FzlSc','Culinary'),
  ('DDgtJ_-Sb--','Sponsored'),
  ('DDtVIbZP37l','Paket Narasi Daerah'),
  ('DE68APmzf3b','Lifestyle'),
  ('DE9hhCqSZm-','Sponsored'),
  ('DEEtjwRSIva','Tourism'),
  ('DEGhoVUTMK4','Lifestyle'),
  ('DEHeeV3y9IN','Culinary'),
  ('DEID2Ffy5nk','Lifestyle'),
  ('DEMa5div-jo','Paket Narasi Daerah'),
  ('DEQDM4BTk_N','Lifestyle'),
  ('DE_vxRET_my','Lifestyle'),
  ('DEhO7rpSF-A','Tourism'),
  ('DEmbLC-ynKO','Tourism'),
  ('DEmeLkpTYSG','Lifestyle'),
  ('DEuY9BhSUsz','Event'),
  ('DEwxoely2gl','Tourism'),
  ('DFHBxy5TOsw','Tourism'),
  ('DFHSQeByc_9','Sponsored'),
  ('DFIMbncyQFq','Culture'),
  ('DFPC1qQz0Mm','Regional'),
  ('DFeN0VBTZKl','Regional'),
  ('DFkUV2DzP0m','Lifestyle'),
  ('DG3AgYYyyAI','Culinary'),
  ('DG49SLsyOn8','Culture'),
  ('DGR-a11yger','Regional'),
  ('DGR9rqqyoPQ','Regional'),
  ('DGRldwuyr4E','Regional'),
  ('DHCiEi8zFpx','Regional'),
  ('DHF7eCYSGXy','Sponsored'),
  ('DHVoadLyscz','Culture'),
  ('DHalBiWTbpP','Regional'),
  ('DHfW-HszDYL','Regional'),
  ('DHoLzViSBLh','Regional'),
  ('DHpsOCGTAe-','Sponsored'),
  ('DHpzZLBSdNw','Sponsored'),
  ('DHs3d0azSCl','Sponsored'),
  ('DIFkfM5yD28','Event'),
  ('DIvmOd_ywUK','Lifestyle'),
  ('DJgJDlfzSWc','Lifestyle'),
  ('DJwHpAfTwvK','Tourism'),
  ('DKO03x_uGtp','Tourism'),
  ('DKUNwsqTss4','Lifestyle'),
  ('DKUXa7KT40R','Regional'),
  ('DKb5HNQTW98','Lifestyle'),
  ('DKx9LduSzF7','Tourism'),
  ('DLCg_AIBaN5','People'),
  ('DLFXkB6J1p_','Regional'),
  ('DLPZPDmTPmU','Lifestyle'),
  ('DM4_JQIxpxW','Tourism'),
  ('DM9OwTkyhiD','Tourism'),
  ('DM9dGZmzNV4','Regional'),
  ('DMFVUlAyId0','Tourism'),
  ('DMOr3IxSEUT','Regional'),
  ('DN-oWAGAY0S','Event'),
  ('DN2-S5dUp1U','Event'),
  ('DNC-gEFSwSh','Sponsored'),
  ('DNDJNFKSxYZ','Tourism'),
  ('DNKhCojSHLg','Sponsored'),
  ('DNS_jdMy5qF','Sponsored'),
  ('DNclAdoT9sd','Sponsored'),
  ('DNddDArvKwD','Sponsored'),
  ('DNkyv9nvBlb','Sponsored'),
  ('DOGMrU5km1g','Sponsored'),
  ('DOOKr37EtL_','Culture'),
  ('DOQOPEHAdc3','Event'),
  ('DOSekzPgZiE','Event'),
  ('DOd3AjOgTvD','Sponsored'),
  ('DOhwNilkxq9','Sponsored'),
  ('DP0vZSdkvG1','Lifestyle'),
  ('DP6C8neEnWo','Sponsored'),
  ('DP6H6csEgX-','Sponsored'),
  ('DP8THg4EeAu','Tourism'),
  ('DPGZLsTkRtC','Event'),
  ('DPKl2WCknzy','Event'),
  ('DPaywwCE3qk','Sponsored'),
  ('DQBqSmyDvsX','Regional'),
  ('DQOEXWKkRHt','Lifestyle'),
  ('DQTUP_XkjQM','Regional'),
  ('DQjnLbVkw2x','Tourism'),
  ('DQrB89iEtLJ','Sponsored'),
  ('DSUfB4QD3sG','Sponsored'),
  ('DSxS8IjE4I7','Tourism'),
  ('DTb1xQTEjIo','Regional'),
  ('DU6fPjzEzP1','Culture'),
  ('DU7fck0kY23','Culture'),
  ('DU84yTdk_-O','Culture'),
  ('DUN7iFSEoXm','Tourism'),
  ('DU_c97ck4bX','Culture'),
  ('DUauW0KkiON','People'),
  ('DV-9TpGkndG','Lifestyle'),
  ('DV0Pi0HTsys','Culture'),
  ('DV76d13zspq','Culture'),
  ('DV8LqKlzP6-','Culture'),
  ('DV9bK8QEzC9','Culture'),
  ('DVBACGaiTpC','Regional'),
  ('DVJAHUvEn2J','Culture'),
  ('DVTmcHiktC-','Culture'),
  ('DVgPikLE7N4','Culture'),
  ('DVi3qZ7k1ny','Culture'),
  ('DVxOirHEve-','Event'),
  ('DVziiLYE5L5','Regional'),
  ('DXZY8cXCcJ9','Regional'),
  ('DXdrBYdj-CW','Tourism'),
  ('DXdwm-XjgEd','Sponsored'),
  ('DXdzUJlEfN4','Tourism'),
  ('DY-Fj9ayELw','Tourism'),
  ('DYbUNOypxwL','Sponsored'),
  ('DZ-FG1eP-xO','Culinary'),
  ('DZ1CStzpFCH','Tourism'),
  ('DZ2fWG8Ph8V','Tourism'),
  ('DZ9_iapJ3BU','Tourism'),
  ('DZGwaszTECT','Regional'),
  ('DZHsl_ZTQGI','Sponsored'),
  ('DZoyaZMhRLO','Tourism'),
  ('DZpL7hZBRBu','Tourism'),
  ('DZu2aNEhvkr','Tourism'),
  ('DZuYp-Rp7i2','Tourism'),
  ('Da9IfJyTIF5','Lifestyle'),
  ('DaDUSqzp1ek','Tourism'),
  ('DaEZ2Koz4jc','People'),
  ('DacGl5SBa4x','Tourism'),
  ('Dal_pSyTdMO','People'),
  ('Dauv99eBUFx','Sponsored'),
  ('DbLlMzozlam','Tourism'),
  ('DbmWDbvPd97','x'),
  ('DbqYUyZB5FN','Lifestyle')
) as v(shortcode, category)
 where (r.permalink like '%/' || v.shortcode || '/%'
     or r.permalink like '%/' || v.shortcode)
   and r.category is distinct from v.category;
