-- Which brand a reel is for, so Video Story can be filtered by sponsor
-- rather than by which account happened to post it.
--
-- Chips of account usernames were the wrong axis: a reader looking for the
-- Honda work does not know or care that it went out from gorontalo.unite.
--
-- The values come from the mentions already extracted in the local archive,
-- and each reel takes the one that recurs most across the whole archive --
-- a post naming four accounts is for the sponsor, not for the venue tagged
-- alongside it. Mentions seen only once are left out: a single appearance is
-- a guest, not a sponsor. 344 of 1165 reels get a brand.
--
-- Nullable by design. Most reels have no sponsor, and that is not missing data.

alter table public.reels
  add column if not exists brand text;

comment on column public.reels.brand is
  'Sponsor or partner the reel is for, from mentions in the caption. Null when there is none -- most reels.';

create index if not exists reels_brand_idx on public.reels (brand) where brand is not null;

update public.reels as r
   set brand = b.name
  from (values
  ('C-3-KWRPbbK','Honda Outside Java'),
  ('C-3snDfhfqK','Pemerintah Provinsi Gorontalo'),
  ('C-G57eBBwmL','Pemerintah Provinsi Gorontalo'),
  ('C-IAQ8kPjVN','Digiplus'),
  ('C-MF5wwhmD8','Pemerintah Provinsi Gorontalo'),
  ('C-TzTWpBgTy','Pemerintah Provinsi Gorontalo'),
  ('C-ZI4nFhms7','Pemerintah Provinsi Gorontalo'),
  ('C-eGzzfBn9m','Pemerintah Provinsi Gorontalo'),
  ('C-lrJkEJ1mY','Pemerintah Provinsi Gorontalo'),
  ('C-q0t5gJ5DD','Pemerintah Provinsi Gorontalo'),
  ('C-v8r6hh4WM','Pemerintah Provinsi Gorontalo'),
  ('C0LVmynh9jY','Synergi'),
  ('C1ZhE8rBjH2','Synergi'),
  ('C2MUdPLyWzy','The Palace'),
  ('C2MhHI6Sska','Rachmat Gobel'),
  ('C2OiZ1RS_9T','ACE Hardware'),
  ('C2hAeewywdk','Rachmat Gobel'),
  ('C2luyP1y2tw','GRAB'),
  ('C3cgzn0yaMX','like_gorontalo'),
  ('C3oXPjDBPxP','ACE Hardware'),
  ('C3v5ck_hH4I','Brilikids'),
  ('C3zf0KAhm-B','ERHA'),
  ('C4FWOozB6z9','Rachmat Gobel'),
  ('C4zayF2B1YI','GRAB'),
  ('C5-2xfehD-W','ACE Hardware'),
  ('C5ZwlpPhzzZ','loka_gorontalo'),
  ('C5e6yl5hTd5','duniadronegorontalo'),
  ('C5s6jTvhxco','coolturnesia'),
  ('C6At8tRyQ8s','like_gorontalo'),
  ('C6C70h6hWeJ','jokowi'),
  ('C6d4tzHSl7M','iBox'),
  ('C7Rd9G8hIgM','duniadronegorontalo'),
  ('C8O-5Wpv9fL','3Second'),
  ('C8dWH5NBXcO','Pemerintah Provinsi Gorontalo'),
  ('C9UpqGlynlc','1000 Guru Gorontalo'),
  ('CYxSkQIhQe5','oeloe_mile'),
  ('CZ08Ivph-I0','villa.kencana'),
  ('CZi0HReBn0x','rahmatya_tangguda'),
  ('CZnsEjxhqbw','mohamadtaufik25'),
  ('CZqowTshQgf','melikapanigoro'),
  ('C_O8C96BHJs','Pemerintah Provinsi Gorontalo'),
  ('C_U39CCBR9v','Pemerintah Provinsi Gorontalo'),
  ('C_b6DWvh7kv','Pemerintah Provinsi Gorontalo'),
  ('C_g8WS5Bu4_','Pemerintah Provinsi Gorontalo'),
  ('C_hj_SmB6c4','ERHA'),
  ('C_kxZhwhXPe','Wulling'),
  ('C_mUDdQBIGw','Pemerintah Provinsi Gorontalo'),
  ('C_t6mq9pjag','Pemerintah Provinsi Gorontalo'),
  ('C_zBu4ap9mb','Pemerintah Provinsi Gorontalo'),
  ('CcAKhVQAEiI','y_lihawa'),
  ('CecglUCrgns','sandiuno'),
  ('Cf8VwJ9gMY8','rifaldius'),
  ('CfJEzy7AM5S','vinaluciabanua'),
  ('CfOF-00gH42','sintiamci6'),
  ('CfbQoZNgzO-','ERHA'),
  ('CfnWx5LAsc0','raymoniagaa'),
  ('CfsNlKwgfV5','rully.ahaya'),
  ('CgGpVkKgBml','sintiamci6'),
  ('CgIxxsmgYrc','yunusmuller25'),
  ('CgTmnUIA8-B','reginamagdalena'),
  ('CgWjKQfB5Rb','geryalvaroo'),
  ('Cgd8R1ugVd1','nissamoh'),
  ('Ch3Qb27B8x1','isal_gomic'),
  ('ChEm8-AAyY3','isal_gomic'),
  ('ChJ1ycyAx1C','isal_gomic'),
  ('ChOPHR9AYjv','y_lihawa'),
  ('ChVzZazgham','nandaelba'),
  ('ChWFAbAADWV','isal_gomic'),
  ('ChYpOc5AC0Y','petty_hamz'),
  ('ChvaqA_A1aD','petty_hamz'),
  ('CiCMw69gqdA','festivalikantuna'),
  ('CiDHJAKpoek','festivalikantuna'),
  ('Cib9QCqg37d','rifaldius'),
  ('CieegikgBzs','gisellamukuan'),
  ('Cir6jswA0G-','nurlailaishak'),
  ('Cj142cJgDwZ','rully.ahaya'),
  ('CjOwWzjgJ3S','yunusmuller25'),
  ('CkhHlKXgcJY','nthnplt'),
  ('ClDX-0yA8tn','raymoniagaa'),
  ('Cle4OXKgyFx','lutviyac'),
  ('ClhrXivgL2s','rifaldius'),
  ('CmOCCuVo9ou','fath_zm'),
  ('Cmv--5KhZ3L','ERHA'),
  ('CntJ1UQhTu8','nissamoh'),
  ('Co1CYI2AGKh','tarinaminusta'),
  ('CoUMF8Ag4F5','vian_adam'),
  ('CoUYg-3uJoV','ERHA'),
  ('Cp6mEeFgIT9','fhirmanohihiya'),
  ('Cp6wUzTOCM7','aldi.inaku'),
  ('CpWtwDfyfGg','tarinaminusta'),
  ('CpXECGlSkgi','rbenawan'),
  ('Cp_qKQyohiW','hulonthalo.string.orchestra'),
  ('CpcJDlZujZZ','daeng_manji'),
  ('Cpo34GKO4IK','andi.ishal'),
  ('CponPibgqf9','rolis_asi'),
  ('CppPSSlOAC7','nayahaddar'),
  ('CppWwLjOGTn','hulonthalo.string.orchestra'),
  ('Cq7ftEkoSLu','hidayatullah_daud'),
  ('CqDLNywgmbw','Bank Indonesia'),
  ('CqFEBImgAnz','adi.ilahude'),
  ('CqZCTwjShxq','fathirmohi23'),
  ('CqmxbRZgTCs','orangsusah17'),
  ('CqsDcqZAF9E','Erigo'),
  ('Cr1z9KfAyuF','rostin_baruadi'),
  ('Cr4nf0HglAX','ditelvin'),
  ('Crz3Je-guYt','dokrifki'),
  ('Cs-27UFg4Lx','GRAB'),
  ('Cs47o2QvLYH','ERHA'),
  ('Cs50Dfxgas1','whyurezhaldy'),
  ('Cs7QTCEh0d8','lecka_smenkqiuw'),
  ('CsFxPnEomwj','de_jenglen'),
  ('CsGJgOdoRhP','anis_mustapa'),
  ('CsK486yAg7g','anis_mustapa'),
  ('CsKoFokAmf0','adi.ilahude'),
  ('CsQZ3gUvHqa','de_jenglen'),
  ('CsVb23BgU8-','rostin_baruadi'),
  ('CsXjNqhA0Ft','de_jenglen'),
  ('CsdRPj5Aqw_','whyurezhaldy'),
  ('CslEr68gEVV','anis_mustapa'),
  ('CssiUaoAS7W','Honda Outside Java'),
  ('Ct2-Faxgfpz','srydunggio'),
  ('Ct3SCUWgn8X','GRAB'),
  ('Ct5ajRZuQCD','like_gorontalo'),
  ('Ct9NGjkgi2q','oeloe_mile'),
  ('CtOI52hvBh1','ditelvin'),
  ('CtQG7UiBmOI','adhyy.s'),
  ('CtStXTvBt-x','GRAB'),
  ('CtX6WnPPuRj','de_jenglen'),
  ('CtYgIF6PCP2','villa.kencana'),
  ('CtaamnlA5Xc','rickyharyonodai'),
  ('CtcqgaKB96I','fathirmohi23'),
  ('CtdeHdxhmHl','adhyy.s'),
  ('CtfZ0XbA-Cs','ruslimowuu'),
  ('Ctfh1g5pwOR','GRAB'),
  ('Ctfm_MipWds','yahyaakib'),
  ('CtfvkWeJeBp','ditelvin'),
  ('CtgB6eHAzfw','densee.denis'),
  ('CtgbnjjOZtc','ruslimowuu'),
  ('CtllzruJX-I','ruslimowuu'),
  ('Ctp5m0QPbSn','obossresort'),
  ('Cts5gQxBEpf','adhyy.s'),
  ('CttJ4RGJdjd','whyurezhaldy'),
  ('Cu-68xFhcdG','matris__giu'),
  ('Cu07kCIhF-R','Maxim'),
  ('Cu3-piWhWJ7','ylndadm'),
  ('Cu3CeQphC3M','anis_mustapa'),
  ('CuOahucyARB','densee.denis'),
  ('CuOd4JtSf7U','ditelvin'),
  ('CuOyfdFyshP','nayahaddar'),
  ('CuPSoCYyHWB','sitylalu'),
  ('CuWS-YqBZD3','orangsusah17'),
  ('Cu_IR_fPCk7','delvina05'),
  ('Culb4bHhD0e','whyurezhaldy'),
  ('Cuyv9nKBha_','ririinggo'),
  ('Cv8pyzYvG51','ditelvin'),
  ('CvCJYl6htx4','lutviyac'),
  ('CvHJrlDB0js','amalbdjo'),
  ('CvL-k9lhdmo','pasambaya_river_side'),
  ('CvO3hMZB4Tr','kurenaibeach'),
  ('CvOyV2ah0Te','matris__giu'),
  ('CvPNOcMhtrX','anis_mustapa'),
  ('CvRkJS0BIIZ','melikapanigoro'),
  ('CvUJN5yBGKr','adhyy.s'),
  ('CvbR2TAhJou','jihaanmuhraini'),
  ('CvgtD0-Bjg0','ririinggo'),
  ('CvuA5mghMEB','anis_mustapa'),
  ('CvwlVWbBdAl','kurenaibeach'),
  ('Cw1p1h9htV2','billy_kohler'),
  ('Cw1yKuPRTqj','adhyy.s'),
  ('Cw9TKOWBtpQ','Bank Indonesia'),
  ('CwJVKYehgzI','whyurezhaldy'),
  ('CwMuKQRB4Kl','bagindas'),
  ('Cw_iurLBu3j','orangsusah17'),
  ('CweoE0lhilL','bagindas'),
  ('Cwj5gfXh8Xq','whyurezhaldy'),
  ('CwjbekQB1dG','vian_adam'),
  ('Cwo19NEh4V_','andi.ishal'),
  ('CwpIHUwBrrA','villa.kencana'),
  ('Cx2ZwhLBIj2','Synergi'),
  ('Cx6yAtkypx1','Rachmat Gobel'),
  ('CxM6tsMBt9E','delvina05'),
  ('CxVM3bOhbOs','rumahhantuindonesia'),
  ('CxsehRcyr47','Rachmat Gobel'),
  ('CxveiDiJTCj','Rachmat Gobel'),
  ('CzS_4phvRik','Yulia Hotel'),
  ('CzSsMl4hbKl','Synergi'),
  ('DA0As7lNMSr','tripbarengisal'),
  ('DA2IBaMSQnp','Kemenkumham'),
  ('DA5-cffy8wC','Rachmat Gobel'),
  ('DA5aYGSt9-Q','tripbarengisal'),
  ('DA7Ge73Ja_m','Pemerintah Provinsi Gorontalo'),
  ('DA8KyEfBqRF','Pukis Kota Baru'),
  ('DAC-pP2B12H','Wulling'),
  ('DAFIM_VJbAX','Pemerintah Provinsi Gorontalo'),
  ('DAIYSunBD6U','Wulling'),
  ('DAcTpo1J4pl','Pemerintah Provinsi Gorontalo'),
  ('DAdO8dnSGIl','like_gorontalo'),
  ('DAnnyXBhceR','The Palace'),
  ('DAp_N-IJpoa','Pemerintah Provinsi Gorontalo'),
  ('DB-587yyN0Q','Buccheri'),
  ('DBATx83J9ra','Pemerintah Provinsi Gorontalo'),
  ('DBDPp3dyI5U','like_gorontalo'),
  ('DBDf6RgKr82','tripbarengisal'),
  ('DBP_JBqJnth','Pemerintah Provinsi Gorontalo'),
  ('DBi85jbBKtc','ACE Hardware'),
  ('DBiMUJgBFCs','Pukis Kota Baru'),
  ('DBiYCbIzSKM','Honda Outside Java'),
  ('DBlBpdJSPaX','Rachmat Gobel'),
  ('DBn3vAYsESH','gilbertho_tongotongo'),
  ('DBoGOqmPeP-','Pemerintah Provinsi Gorontalo'),
  ('DBpeepsh47f','Pemerintah Provinsi Gorontalo'),
  ('DBqXH9EBW2s','Gojek'),
  ('DCjbqOLMUGW','Rachmat Gobel'),
  ('DCoLL-OzVgR','Fore Coffee'),
  ('DCoUXfuzZyI','Fore Coffee'),
  ('DCx9uASypuA','Pukis Kota Baru'),
  ('DD02h17ScFT','Bank Indonesia'),
  ('DD8Ur7pTMJ-','Yulia Hotel'),
  ('DD9Y8vlvR_Y','Pemerintah Provinsi Gorontalo'),
  ('DDE957wSbEh','Yulia Hotel'),
  ('DDgtJ_-Sb--','Pukis Kota Baru'),
  ('DDtVIbZP37l','Pemerintah Provinsi Gorontalo'),
  ('DE9hhCqSZm-','Funderland Indonesia'),
  ('DEMa5div-jo','Pemerintah Provinsi Gorontalo'),
  ('DEQDM4BTk_N','yowan_ahmad'),
  ('DFHSQeByc_9','Pukis Kota Baru'),
  ('DFe2UbWSGCb','Funderland Indonesia'),
  ('DFultWqym5z','fenypou'),
  ('DG44PVoyJa6','AZKO'),
  ('DGSTBv8S7s9','Indogrosir'),
  ('DGSTV2VSUDf','Indogrosir'),
  ('DGx1OhLSo_r','gilbertho_tongotongo'),
  ('DHF2VNyScIY','Muraa Gorontalo'),
  ('DHF7eCYSGXy','Pukis Kota Baru'),
  ('DHQQWrbSEMs','Buccheri'),
  ('DHlGtT8yP7h','Pohuwato Half Marathon'),
  ('DHndKiEyTG9','AZKO'),
  ('DHp_5P9yl8d','Bank Indonesia'),
  ('DHpsOCGTAe-','Bank Indonesia'),
  ('DHpzZLBSdNw','Indogrosir'),
  ('DHs3d0azSCl','loka_gorontalo'),
  ('DIA_9QkStW5','Pohuwato Half Marathon'),
  ('DIsi-Muycks','AZKO'),
  ('DJ4ErV9z-tO','Modena Home Center'),
  ('DKUNwsqTss4','fleur_clothing.mdc'),
  ('DKWQzEttJpw','asyrafalamri_official'),
  ('DKwDnOjThHq','AZKO'),
  ('DLE37RXO6MZ','Smartfren'),
  ('DLEM-qsTIbG','Indogrosir'),
  ('DLEid8pvtTv','likein_gorontalo'),
  ('DLPZPDmTPmU','mrarvy'),
  ('DLboIuZu7he','Everbest'),
  ('DLojqN1tILU','goproid'),
  ('DLrUUH2P5Lf','goproid'),
  ('DM7WobLzSGl','Platinum Cellular'),
  ('DM9dGZmzNV4','Imigrasi Gorontalo'),
  ('DMFVUlAyId0','mrarvy'),
  ('DMOr3IxSEUT','Imigrasi Gorontalo'),
  ('DMOzOVhy1TZ','Cititex'),
  ('DN-oWAGAY0S','Rachmat Gobel'),
  ('DN2yLqGZnHF','Platinum Cellular'),
  ('DN7Up93k9Jv','El Production'),
  ('DNC-gEFSwSh','Smartfren'),
  ('DNKhCojSHLg','Onato by Swiss18'),
  ('DNS_jdMy5qF','Onato by Swiss18'),
  ('DNclAdoT9sd','Platinum Cellular'),
  ('DNddDArvKwD','Onato by Swiss18'),
  ('DNkVMmbzmaK','Platinum Cellular'),
  ('DNkyv9nvBlb','syabab.ofcl'),
  ('DO0a7XBEiCQ','Honda Outside Java'),
  ('DO79VhQjjv9','GRAB'),
  ('DOGZSf-E6sO','Platinum Cellular'),
  ('DOQOPEHAdc3','Rachmat Gobel'),
  ('DOSekzPgZiE','Rachmat Gobel'),
  ('DOd3AjOgTvD','Yulia Hotel'),
  ('DOfa-ITk6qo','El Production'),
  ('DOhwNilkxq9','El Production'),
  ('DOuUOD0Eudy','Hasjrat Toyota'),
  ('DP0yCsckkRz','Modena Home Center'),
  ('DP6C8neEnWo','Suara Tana Timur'),
  ('DP6H6csEgX-','Suara Tana Timur'),
  ('DPGEm4zkgyn','El Production'),
  ('DPaywwCE3qk','El Production'),
  ('DQBPW9jjlm_','Road Show Kuliner Viral'),
  ('DQG6QcqEmfv','Hasjrat Toyota'),
  ('DQJUKEGkYD-','Road Show Kuliner Viral'),
  ('DQTUP_XkjQM','Imigrasi Gorontalo'),
  ('DQrB89iEtLJ','rumahhantuindonesia'),
  ('DRB9EkxktcW','olymplast'),
  ('DRBzRnFkuAC','olymplast'),
  ('DRE4OJOj-Zf','dkijalanjalan'),
  ('DS5GdsPkkMm','loka_gorontalo'),
  ('DSHJlxsEox5','Modena Home Center'),
  ('DSPSKXWEkuf','Everbest'),
  ('DSUfB4QD3sG','Gebyar Kuliner'),
  ('DSXdazPkuaI','Himakom UNG'),
  ('DSXeRcuktMW','Himakom UNG'),
  ('DSXeXAZktIe','Himakom UNG'),
  ('DSY658lEuzN','Everbest'),
  ('DScH04AklrD','Gebyar Kuliner'),
  ('DSeV9aykov3','Bintang'),
  ('DSeXhMXElS1','Bintang'),
  ('DSo8fs9ksvW','Buccheri'),
  ('DSzNxxnj3Qd','reskazs'),
  ('DSzhMSFko_k','Everbest'),
  ('DThO2JlkmYI','Bintang'),
  ('DU6fPjzEzP1','papipcelebes'),
  ('DU84yTdk_-O','papipcelebes'),
  ('DU_c97ck4bX','papipcelebes'),
  ('DV0Pi0HTsys','papipcelebes'),
  ('DV6KVNUk8K2','papipcelebes'),
  ('DV76d13zspq','papipcelebes'),
  ('DV8LqKlzP6-','papipcelebes'),
  ('DV9bK8QEzC9','papipcelebes'),
  ('DVDpY4SE3sO','papipcelebes'),
  ('DVGfIWFku0o','papipcelebes'),
  ('DVJAHUvEn2J','papipcelebes'),
  ('DVLlz8pEs5S','papipcelebes'),
  ('DVQO85Zkv8_','AZKO'),
  ('DVQy1b6ktDm','papipcelebes'),
  ('DVTmcHiktC-','papipcelebes'),
  ('DVgPikLE7N4','papipcelebes'),
  ('DVk9FGGT2pg','Buccheri'),
  ('DVqa7dGD1pB','Alfamart'),
  ('DVssWjKDs7J','Hasjrat Toyota'),
  ('DVyCk6dE4Mr','iBox'),
  ('DWiwLXOji70','rumahhantuindonesia'),
  ('DXZY8cXCcJ9','Imigrasi Gorontalo'),
  ('DXdtEjADlUC','Honda Outside Java'),
  ('DXdwm-XjgEd','rumahhantuindonesia'),
  ('DYJXI99uALJ','sog.gorontalo.official'),
  ('DYbUNOypxwL','sog.gorontalo.official'),
  ('DYmSrLsJBSc','3Second'),
  ('DZ4hQp-Tpmg','Everbest'),
  ('DZHsl_ZTQGI','3Second'),
  ('DZoyaZMhRLO','Rachmat Gobel'),
  ('DZpL7hZBRBu','Rachmat Gobel'),
  ('DZu2aNEhvkr','Rachmat Gobel'),
  ('DZzrwscS50S','Rachmat Gobel'),
  ('Da4g8ahyrVR','Bank Indonesia'),
  ('DaAFo6UzD_W','Everbest'),
  ('Dahq2YHTEnF','Free Wifi Movie'),
  ('Dal_pSyTdMO','Rachmat Gobel'),
  ('Dauv99eBUFx','Bank Indonesia')
) as b(shortcode, name)
 where r.permalink like '%/' || b.shortcode || '/%'
    or r.permalink like '%/' || b.shortcode;
